### ISSUE TITLE
Can't find few files in src folder 

### ISSUE THREAD

**Issue by danyan1** [zijin-gu/NeuroGen#1]
I have forked the NeuroGen repo, and I find there is a problem. The problem codes located in lines 15-16 of 'src/data_preparation.py' file are copied below, and I am afraid it is mainly because that the author might miss uploading the 'lasagne_utility.py' file which should be located in the 'src' folder.

from src.lasagne_utility import deconv, conv, batch_norm, batch_norm_n, fc_concat, \
    conv_concat, avg, flatten, sigmoid, tanh
from src.lasagne_utility import print_lasagne_network

**Comment by danyan1** [comment]
also the line 244 of the src/data_preparation.py file
'from gaborizer.src.gabor_feature_dictionaries import gabor_feature_maps'
there is also no gabor_feature_dictionaries file.

**Comment by zijin-gu** [comment]
Hi, actually the data_preparation.py is not used in this paper and that file should be deleted. Sorry for the confusing.
