### ISSUE TITLE
no image transform procedurs

### ISSUE THREAD

**Issue by danyan1** [zijin-gu/NeuroGen#2]
Hello Gu,

I find that you use _"S%d_stimuli_227.h5py" % subject_  in "fwrf_ROIvoxel_mean.py" file (line 119), which I guess might be the result after the transforms of images (normalized, RandomResizedCrop, etc), but I didn't find the relevant function or file to do this. The "227" represents what?

Could you attach this part of processing?

Thank you.

**Comment by zijin-gu** [comment]
Hi,

227 just means the images are cropped to have size 227 x 277 x 3. you can find the relevant code here: https://github.com/styvesg/nsd
