### ISSUE TITLE
Lack of the code about calculating the optimized synthetic images

### ISSUE THREAD

**Issue by danyan1** [zijin-gu/NeuroGen#3]
Hello, Gu,

I find you use the top 10 synthetic images in NeuroGen, the corresponding code is in the line 117 in your neurogen file. "top_idx = np.load('./img/S%d' % args.subj + '/top10_class.npy')". But there is not related code or results of the top 10 synthetic images in your repository.

Could you please attach this part?

Thank you so much.
Qin

**Comment by zijin-gu** [comment]
hi,

as reported in the paper, the top 10 classes were picked by rank order the predictions from the encoding model. you can generate your top classes based on your own encoding models. or if you just want to test, you can randomly select classes from Imagenet.
