### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by sbkim052** [zijin-gu/NeuroGen#4]
Hi, thanks for sharing this wonderful work.
Could you tell me which dataset you used in the NSD dataset for training the fwRF model?

Thanks.

![image](https://user-images.githubusercontent.com/59387731/163704548-f8f60999-3695-41ed-9fb0-ce8d502ad36d.png)

**Comment by zijin-gu** [comment]
Hi,

please refer to the nsd data description where there is a detailed explanation of the dataset. in our paper we were using the GLM denoised data.

**Comment by sbkim052** [comment]
Hi, Could you share the code for training encoding model?
